-- MySQL Script generated by MySQL Workbench
-- Wed Aug  3 20:42:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
    'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Table `a_shop`.`ax_document_fin_invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a_shop`.`ax_document_fin_invoice`;

CREATE TABLE IF NOT EXISTS `a_shop`.`ax_document_fin_invoice`
(
    `id`                        BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid`                      VARCHAR(100)        NOT NULL,
    `counterparty_id`           BIGINT(20) UNSIGNED NOT NULL,
    `fin_transaction_type_id`   BIGINT(20) UNSIGNED NOT NULL,
    `catalog_payment_status_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
    `payment_order_id`          VARCHAR(100)        NULL DEFAULT NULL,
    `status`                    TINYINT(1) UNSIGNED NULL DEFAULT 0,
    `created_at`                INT(11) UNSIGNED    NULL DEFAULT NULL,
    `updated_at`                INT(11) UNSIGNED    NULL DEFAULT NULL,
    `deleted_at`                INT(11) UNSIGNED    NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `uuid`, `counterparty_id`, `fin_transaction_type_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
    INDEX `fk_ax_document_order_ax_counterparty1_idx` (`counterparty_id` ASC),
    INDEX `fk_ax_document_order_ax_fin_transaction_type1_idx` (`fin_transaction_type_id` ASC),
    INDEX `fk_ax_document_order_ax_catalog_payment_status1_idx` (`catalog_payment_status_id` ASC),
    CONSTRAINT `fk_ax_document_order_ax_counterparty10`
        FOREIGN KEY (`counterparty_id`)
            REFERENCES `a_shop`.`ax_counterparty` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_ax_document_order_ax_fin_transaction_type10`
        FOREIGN KEY (`fin_transaction_type_id`)
            REFERENCES `a_shop`.`ax_fin_transaction_type` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_ax_document_order_ax_catalog_payment_status10`
        FOREIGN KEY (`catalog_payment_status_id`)
            REFERENCES `a_shop`.`ax_catalog_payment_status` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `a_shop`.`ax_document_fin_invoice_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a_shop`.`ax_document_fin_invoice_content`;

CREATE TABLE IF NOT EXISTS `a_shop`.`ax_document_fin_invoice_content`
(
    `id`                 BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `catalog_product_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
    `catalog_storage_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
    `document_id`        BIGINT(20) UNSIGNED NULL DEFAULT NULL,
    `price`              DECIMAL UNSIGNED    NULL DEFAULT 0.0,
    `quantity`           INT(11) UNSIGNED    NULL DEFAULT 1,
    `description`        VARCHAR(255)        NULL DEFAULT NULL,
    `created_at`         INT(11) UNSIGNED    NULL DEFAULT NULL,
    `updated_at`         INT(11) UNSIGNED    NULL DEFAULT NULL,
    `deleted_at`         INT(11) UNSIGNED    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_ax_document_order_content_ax_catalog_product1_idx` (`catalog_product_id` ASC),
    INDEX `fk_ax_document_order_content_ax_catalog_storage1_idx` (`catalog_storage_id` ASC),
    INDEX `fk_ax_document_fin_invoice_content_ax_document_fin_invoice1_idx` (`document_id` ASC),
    CONSTRAINT `fk_ax_document_order_content_ax_catalog_product10`
        FOREIGN KEY (`catalog_product_id`)
            REFERENCES `a_shop`.`ax_catalog_product` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_ax_document_order_content_ax_catalog_storage10`
        FOREIGN KEY (`catalog_storage_id`)
            REFERENCES `a_shop`.`ax_catalog_storage` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_ax_document_fin_invoice_content_ax_document_fin_invoice1`
        FOREIGN KEY (`document_id`)
            REFERENCES `a_shop`.`ax_document_fin_invoice` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
